### ISSUE TITLE
Matrix bug?

### ISSUE THREAD

**Issue by luksen99** [johntfoster/bspline#4]
Hi Johnt, 
we are using your B-spline package in the framework of tackling parabolic differential equations. 
Creating a spline matrix A using ‘collmat’ we find that the last entry (A_nn) is, just like the entire last row 0. Is this a bug? We expected  the entire row to be 0, **except** for the A_nn element, which should be 1. (Just like the A_00 element is 1 and the rest of the A_0-row is 0). Right now we do some ‘artificial fixing’, i.e. setting A_nn to 1 manually.
The problem is also present in the 1st order derivative.

**Comment by Technologicat** [comment]
Hi,
The bspline package defines each piecewise polynomial to have support on the half-open interval [x_k, x_{k+1}). Hence, evaluating the last basis function at the final endpoint yields 0, making the whole B-spline zero there.

As a workaround, in my own codes I've scaled the whole interval (which is to be spanned by the B-spline) by a factor of 1 + ε, where ε is some suitably small positive number. Then evaluating the last basis function at the *original* endpoint yields a value that is sufficiently close to 1 for practical purposes - and hence evaluating the whole B-spline there then gives sensible results.

I think it is theoretically possible to fix the issue, but doing so complicates the (currently very short and elegant) implementation of the Cox - de Boor algorithm. However, if you and John feel this is important to fix, it could be done.
